package rc_rules;

import cn.javabook.chapter05.entity.LoginEvent
import cn.javabook.chapter05.service.EventService
import cn.javabook.chapter05.service.OrderService
import cn.javabook.chapter05.service.UserService

global EventService eventService
global OrderService orderService
global UserService userService

// 当月消费金额
rule "rc_buy_money"
    no-loop false
    lock-on-active true
    when
        $event : LoginEvent(level == 0);
    then
        if (0 == orderService.getBuyMoneyCurrentMonth($event.getUsername())) {
            // 保存风险事件
            boolean flag1 = eventService.insertRiskEvent($event, "用户当月消费金额为0");
            // 锁定用户账户
            boolean flag2 = userService.lock($event.getUsername());
            if (flag1 && flag2) {
                System.out.println("用户当月消费异常，锁定成功");
            }
            delete($event);
        }
end
