package rc_rules;

import cn.javabook.chapter05.entity.LoginEvent
import cn.javabook.chapter05.service.EventService

global EventService eventService

// 每次都登录都会执行
rule "rc_login"
    no-loop false
    lock-on-active true
    when
        $event : LoginEvent(level == 0)
    then
        boolean flag = eventService.insertEvent($event);
        if (flag) {
            System.out.println("保存用户登录事件");
            delete($event);
        }
end
